name: Generate Graphics

# Only runs when manually triggered
on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (including your script)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make the script executable (chmod +x)
      - name: Make script executable
        run: chmod +x ./generate_graphics.sh

      # Run the script
      - name: Run generate_graphics.sh
        run: ./generate_graphics.sh

      # Commit and push the changes (graphics folder) back to the repo
      - name: Commit and Push changes
        run: |
          git config --global user.name "Vishal Kaleria"
          git config --global user.email "w3vish@gamil.com"
          git add .
          git commit -m "Add/Update graphics folder"
          git push origin main
