name: Sync Graphics Folder

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  sync-graphics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout `sprites` repository
      uses: actions/checkout@v3
      with:
        repository: ViSurya/sprites
        # token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone PIFDexFiles repository
      run: git clone --depth 1 --filter=blob:none --sparse https://github.com/ViSurya/PIFDexFiles.git pifdexfiles

    - name: Fetch only the graphics folder
      run: |
        cd pifdexfiles
        git sparse-checkout init --cone
        git sparse-checkout set graphics

    - name: Copy graphics folder to sprites repo
      run: |
        cp -r pifdexfiles/graphics ./graphics

    - name: Commit and push changes to sprites
      run: |
        git config --global user.name "Vishal Kaleria"
        git config --global user.email "w3vish@gmail.com"
        git add graphics
        git commit -m "Sync graphics folder"
        git push origin main
